# Generated by Django 4.0.4 on 2022-06-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shawer_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
